# -*- coding: utf-8 -*-
"""Assignment-13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_8jbaIsoIcPbAoHX5AxTt5bbboSQCNz
"""

import numpy as np
import matplotlib.pyplot as plt

def bayes_theorem(p_e1,p_e2,p_xgiven_e1,p_xgiven_e2):
	p_x= p_e1*p_xgiven_e1 + p_e2*p_xgiven_e2
	numerator1 = p_e1*p_xgiven_e1
	p_e1given_x=numerator1/p_x
	return p_e1given_x

#Probability that the item is produced by machine A
p_1 = 0.6
#Probability that the item is produced by machine B
p_2 = 1 - p_1
#Probability that the defective item is produced by machine A
p_defective_A = 0.02
#Probability that the defective item is produced by machine B
p_defective_B = 0.01

#Probability that the chosen defective item was produced by machine B
Pr = bayes_theorem(p_2,p_1,p_defective_B,p_defective_A)

print(Pr)